[2022-11-04 12:46:50 +0100] [51697] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f2f355777f0>
  on_reload: <function OnReload.on_reload at 0x7f2f35577910>
  when_ready: <function WhenReady.when_ready at 0x7f2f35577a30>
  pre_fork: <function Prefork.pre_fork at 0x7f2f35577b50>
  post_fork: <function Postfork.post_fork at 0x7f2f35577c70>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f2f35577d90>
  worker_int: <function WorkerInt.worker_int at 0x7f2f35577eb0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f2f3559c040>
  pre_exec: <function PreExec.pre_exec at 0x7f2f3559c160>
  pre_request: <function PreRequest.pre_request at 0x7f2f3559c280>
  post_request: <function PostRequest.post_request at 0x7f2f3559c310>
  child_exit: <function ChildExit.child_exit at 0x7f2f3559c430>
  worker_exit: <function WorkerExit.worker_exit at 0x7f2f3559c550>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f2f3559c670>
  on_exit: <function OnExit.on_exit at 0x7f2f3559c790>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-04 12:46:50 +0100] [51697] [INFO] Starting gunicorn 20.1.0
[2022-11-04 12:46:50 +0100] [51697] [DEBUG] Arbiter booted
[2022-11-04 12:46:50 +0100] [51697] [INFO] Listening at: http://0.0.0.0:8000 (51697)
[2022-11-04 12:46:50 +0100] [51697] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-04 12:46:50 +0100] [51699] [INFO] Booting worker with pid: 51699
[2022-11-04 12:46:50 +0100] [51700] [INFO] Booting worker with pid: 51700
[2022-11-04 12:46:50 +0100] [51702] [INFO] Booting worker with pid: 51702
[2022-11-04 12:46:50 +0100] [51703] [INFO] Booting worker with pid: 51703
[2022-11-04 12:46:50 +0100] [51705] [INFO] Booting worker with pid: 51705
[2022-11-04 12:46:50 +0100] [51697] [DEBUG] 5 workers
[2022-11-04 12:46:51 +0100] [51699] [INFO] Started server process [51699]
[2022-11-04 12:46:51 +0100] [51699] [INFO] Waiting for application startup.
[2022-11-04 12:46:51 +0100] [51703] [INFO] Started server process [51703]
[2022-11-04 12:46:51 +0100] [51703] [INFO] Waiting for application startup.
[2022-11-04 12:46:51 +0100] [51700] [INFO] Started server process [51700]
[2022-11-04 12:46:51 +0100] [51700] [INFO] Waiting for application startup.
[2022-11-04 12:46:51 +0100] [51705] [INFO] Started server process [51705]
[2022-11-04 12:46:51 +0100] [51705] [INFO] Waiting for application startup.
[2022-11-04 12:46:51 +0100] [51702] [INFO] Started server process [51702]
[2022-11-04 12:46:51 +0100] [51702] [INFO] Waiting for application startup.
[2022-11-04 12:46:52 +0100] [51703] [INFO] Application startup complete.
[2022-11-04 12:46:52 +0100] [51702] [INFO] Application startup complete.
[2022-11-04 12:46:52 +0100] [51700] [INFO] Application startup complete.
[2022-11-04 12:46:52 +0100] [51699] [INFO] Application startup complete.
[2022-11-04 12:46:52 +0100] [51705] [INFO] Application startup complete.
[2022-11-04 13:24:58 +0100] [51697] [INFO] Handling signal: term
[2022-11-04 13:24:58 +0100] [51705] [INFO] Shutting down
[2022-11-04 13:24:58 +0100] [51699] [INFO] Shutting down
[2022-11-04 13:24:58 +0100] [51702] [INFO] Shutting down
[2022-11-04 13:24:58 +0100] [51700] [INFO] Shutting down
[2022-11-04 13:24:58 +0100] [51703] [INFO] Shutting down
[2022-11-04 13:24:58 +0100] [51705] [INFO] Waiting for application shutdown.
[2022-11-04 13:24:58 +0100] [51705] [INFO] Application shutdown complete.
[2022-11-04 13:24:58 +0100] [51705] [INFO] Finished server process [51705]
[2022-11-04 13:24:58 +0100] [51705] [INFO] Worker exiting (pid: 51705)
[2022-11-04 13:24:58 +0100] [51699] [INFO] Waiting for application shutdown.
[2022-11-04 13:24:58 +0100] [51699] [INFO] Application shutdown complete.
[2022-11-04 13:24:58 +0100] [51699] [INFO] Finished server process [51699]
[2022-11-04 13:24:58 +0100] [51699] [INFO] Worker exiting (pid: 51699)
[2022-11-04 13:24:58 +0100] [51702] [INFO] Waiting for application shutdown.
[2022-11-04 13:24:58 +0100] [51702] [INFO] Application shutdown complete.
[2022-11-04 13:24:58 +0100] [51702] [INFO] Finished server process [51702]
[2022-11-04 13:24:58 +0100] [51702] [INFO] Worker exiting (pid: 51702)
[2022-11-04 13:24:58 +0100] [51700] [INFO] Waiting for application shutdown.
[2022-11-04 13:24:58 +0100] [51700] [INFO] Application shutdown complete.
[2022-11-04 13:24:58 +0100] [51700] [INFO] Finished server process [51700]
[2022-11-04 13:24:58 +0100] [51700] [INFO] Worker exiting (pid: 51700)
[2022-11-04 13:24:58 +0100] [51703] [INFO] Waiting for application shutdown.
[2022-11-04 13:24:58 +0100] [51703] [INFO] Application shutdown complete.
[2022-11-04 13:24:58 +0100] [51703] [INFO] Finished server process [51703]
[2022-11-04 13:24:58 +0100] [51703] [INFO] Worker exiting (pid: 51703)
[2022-11-04 13:24:58 +0100] [51697] [INFO] Shutting down: Master
[2022-11-04 13:24:59 +0100] [56588] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f42205477f0>
  on_reload: <function OnReload.on_reload at 0x7f4220547910>
  when_ready: <function WhenReady.when_ready at 0x7f4220547a30>
  pre_fork: <function Prefork.pre_fork at 0x7f4220547b50>
  post_fork: <function Postfork.post_fork at 0x7f4220547c70>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f4220547d90>
  worker_int: <function WorkerInt.worker_int at 0x7f4220547eb0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f422056c040>
  pre_exec: <function PreExec.pre_exec at 0x7f422056c160>
  pre_request: <function PreRequest.pre_request at 0x7f422056c280>
  post_request: <function PostRequest.post_request at 0x7f422056c310>
  child_exit: <function ChildExit.child_exit at 0x7f422056c430>
  worker_exit: <function WorkerExit.worker_exit at 0x7f422056c550>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f422056c670>
  on_exit: <function OnExit.on_exit at 0x7f422056c790>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-04 13:24:59 +0100] [56588] [INFO] Starting gunicorn 20.1.0
[2022-11-04 13:24:59 +0100] [56588] [DEBUG] Arbiter booted
[2022-11-04 13:24:59 +0100] [56588] [INFO] Listening at: http://0.0.0.0:8000 (56588)
[2022-11-04 13:24:59 +0100] [56588] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-04 13:24:59 +0100] [56598] [INFO] Booting worker with pid: 56598
[2022-11-04 13:24:59 +0100] [56599] [INFO] Booting worker with pid: 56599
[2022-11-04 13:24:59 +0100] [56600] [INFO] Booting worker with pid: 56600
[2022-11-04 13:24:59 +0100] [56601] [INFO] Booting worker with pid: 56601
[2022-11-04 13:24:59 +0100] [56602] [INFO] Booting worker with pid: 56602
[2022-11-04 13:24:59 +0100] [56588] [DEBUG] 5 workers
[2022-11-04 13:25:00 +0100] [56598] [INFO] Started server process [56598]
[2022-11-04 13:25:00 +0100] [56598] [INFO] Waiting for application startup.
[2022-11-04 13:25:00 +0100] [56600] [INFO] Started server process [56600]
[2022-11-04 13:25:00 +0100] [56600] [INFO] Waiting for application startup.
[2022-11-04 13:25:00 +0100] [56599] [INFO] Started server process [56599]
[2022-11-04 13:25:00 +0100] [56599] [INFO] Waiting for application startup.
[2022-11-04 13:25:00 +0100] [56602] [INFO] Started server process [56602]
[2022-11-04 13:25:00 +0100] [56602] [INFO] Waiting for application startup.
[2022-11-04 13:25:00 +0100] [56601] [INFO] Started server process [56601]
[2022-11-04 13:25:00 +0100] [56601] [INFO] Waiting for application startup.
[2022-11-04 13:25:01 +0100] [56599] [INFO] Application startup complete.
[2022-11-04 13:25:01 +0100] [56600] [INFO] Application startup complete.
[2022-11-04 13:25:01 +0100] [56598] [INFO] Application startup complete.
[2022-11-04 13:25:01 +0100] [56601] [INFO] Application startup complete.
[2022-11-04 13:25:01 +0100] [56602] [INFO] Application startup complete.
[2022-11-04 14:46:42 +0100] [56588] [INFO] Handling signal: term
[2022-11-04 14:46:42 +0100] [56599] [INFO] Shutting down
[2022-11-04 14:46:42 +0100] [56601] [INFO] Shutting down
[2022-11-04 14:46:43 +0100] [56598] [INFO] Shutting down
[2022-11-04 14:46:43 +0100] [56602] [INFO] Shutting down
[2022-11-04 14:46:43 +0100] [56600] [INFO] Shutting down
[2022-11-04 14:46:43 +0100] [56599] [INFO] Waiting for application shutdown.
[2022-11-04 14:46:43 +0100] [56599] [INFO] Application shutdown complete.
[2022-11-04 14:46:43 +0100] [56599] [INFO] Finished server process [56599]
[2022-11-04 14:46:43 +0100] [56599] [INFO] Worker exiting (pid: 56599)
[2022-11-04 14:46:43 +0100] [56601] [INFO] Waiting for application shutdown.
[2022-11-04 14:46:43 +0100] [56601] [INFO] Application shutdown complete.
[2022-11-04 14:46:43 +0100] [56601] [INFO] Finished server process [56601]
[2022-11-04 14:46:43 +0100] [56601] [INFO] Worker exiting (pid: 56601)
[2022-11-04 14:46:43 +0100] [56598] [INFO] Waiting for application shutdown.
[2022-11-04 14:46:43 +0100] [56602] [INFO] Waiting for application shutdown.
[2022-11-04 14:46:43 +0100] [56600] [INFO] Waiting for application shutdown.
[2022-11-04 14:46:43 +0100] [56598] [INFO] Application shutdown complete.
[2022-11-04 14:46:43 +0100] [56602] [INFO] Application shutdown complete.
[2022-11-04 14:46:43 +0100] [56598] [INFO] Finished server process [56598]
[2022-11-04 14:46:43 +0100] [56600] [INFO] Application shutdown complete.
[2022-11-04 14:46:43 +0100] [56602] [INFO] Finished server process [56602]
[2022-11-04 14:46:43 +0100] [56600] [INFO] Finished server process [56600]
[2022-11-04 14:46:43 +0100] [56598] [INFO] Worker exiting (pid: 56598)
[2022-11-04 14:46:43 +0100] [56602] [INFO] Worker exiting (pid: 56602)
[2022-11-04 14:46:43 +0100] [56600] [INFO] Worker exiting (pid: 56600)
[2022-11-04 14:46:43 +0100] [56588] [INFO] Shutting down: Master
[2022-11-07 09:48:48 +0100] [787] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fb800f5f7f0>
  on_reload: <function OnReload.on_reload at 0x7fb800f5f910>
  when_ready: <function WhenReady.when_ready at 0x7fb800f5fa30>
  pre_fork: <function Prefork.pre_fork at 0x7fb800f5fb50>
  post_fork: <function Postfork.post_fork at 0x7fb800f5fc70>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fb800f5fd90>
  worker_int: <function WorkerInt.worker_int at 0x7fb800f5feb0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fb800f84040>
  pre_exec: <function PreExec.pre_exec at 0x7fb800f84160>
  pre_request: <function PreRequest.pre_request at 0x7fb800f84280>
  post_request: <function PostRequest.post_request at 0x7fb800f84310>
  child_exit: <function ChildExit.child_exit at 0x7fb800f84430>
  worker_exit: <function WorkerExit.worker_exit at 0x7fb800f84550>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fb800f84670>
  on_exit: <function OnExit.on_exit at 0x7fb800f84790>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-07 09:48:48 +0100] [787] [INFO] Starting gunicorn 20.1.0
[2022-11-07 09:48:48 +0100] [787] [DEBUG] Arbiter booted
[2022-11-07 09:48:48 +0100] [787] [INFO] Listening at: http://0.0.0.0:8000 (787)
[2022-11-07 09:48:48 +0100] [787] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-07 09:48:48 +0100] [880] [INFO] Booting worker with pid: 880
[2022-11-07 09:48:48 +0100] [901] [INFO] Booting worker with pid: 901
[2022-11-07 09:48:48 +0100] [903] [INFO] Booting worker with pid: 903
[2022-11-07 09:48:48 +0100] [904] [INFO] Booting worker with pid: 904
[2022-11-07 09:48:48 +0100] [905] [INFO] Booting worker with pid: 905
[2022-11-07 09:48:48 +0100] [787] [DEBUG] 5 workers
[2022-11-07 09:48:54 +0100] [880] [INFO] Started server process [880]
[2022-11-07 09:48:54 +0100] [904] [INFO] Started server process [904]
[2022-11-07 09:48:54 +0100] [903] [INFO] Started server process [903]
[2022-11-07 09:48:54 +0100] [880] [INFO] Waiting for application startup.
[2022-11-07 09:48:54 +0100] [904] [INFO] Waiting for application startup.
[2022-11-07 09:48:54 +0100] [903] [INFO] Waiting for application startup.
[2022-11-07 09:48:54 +0100] [901] [INFO] Started server process [901]
[2022-11-07 09:48:54 +0100] [901] [INFO] Waiting for application startup.
[2022-11-07 09:48:54 +0100] [905] [INFO] Started server process [905]
[2022-11-07 09:48:54 +0100] [905] [INFO] Waiting for application startup.
[2022-11-07 09:48:54 +0100] [880] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 89, in _resolve_uri
    results = _resolve(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 43, in _resolve
    return resolver.resolve(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1193, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1063, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 646, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/app.py", line 47, in app_init
    db_client = AsyncIOMotorClient(settings.MONGO_CONNECTION_STRING).credirectDB
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/uri_parser.py", line 542, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 121, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 101, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 97, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

[2022-11-07 09:48:54 +0100] [903] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 89, in _resolve_uri
    results = _resolve(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 43, in _resolve
    return resolver.resolve(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1193, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1063, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 646, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/app.py", line 47, in app_init
    db_client = AsyncIOMotorClient(settings.MONGO_CONNECTION_STRING).credirectDB
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/uri_parser.py", line 542, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 121, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 101, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 97, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

[2022-11-07 09:48:54 +0100] [901] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 89, in _resolve_uri
    results = _resolve(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 43, in _resolve
    return resolver.resolve(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1193, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1063, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 646, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/app.py", line 47, in app_init
    db_client = AsyncIOMotorClient(settings.MONGO_CONNECTION_STRING).credirectDB
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/uri_parser.py", line 542, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 121, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 101, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 97, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

[2022-11-07 09:48:54 +0100] [904] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 89, in _resolve_uri
    results = _resolve(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 43, in _resolve
    return resolver.resolve(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1193, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1063, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 646, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/app.py", line 47, in app_init
    db_client = AsyncIOMotorClient(settings.MONGO_CONNECTION_STRING).credirectDB
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/uri_parser.py", line 542, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 121, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 101, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 97, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

[2022-11-07 09:48:54 +0100] [880] [ERROR] Application startup failed. Exiting.
[2022-11-07 09:48:54 +0100] [903] [ERROR] Application startup failed. Exiting.
[2022-11-07 09:48:54 +0100] [901] [ERROR] Application startup failed. Exiting.
[2022-11-07 09:48:54 +0100] [904] [ERROR] Application startup failed. Exiting.
[2022-11-07 09:48:54 +0100] [903] [INFO] Worker exiting (pid: 903)
[2022-11-07 09:48:54 +0100] [880] [INFO] Worker exiting (pid: 880)
[2022-11-07 09:48:54 +0100] [901] [INFO] Worker exiting (pid: 901)
[2022-11-07 09:48:54 +0100] [904] [INFO] Worker exiting (pid: 904)
[2022-11-07 09:48:54 +0100] [905] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 89, in _resolve_uri
    results = _resolve(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 43, in _resolve
    return resolver.resolve(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1193, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 1063, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/dns/resolver.py", line 646, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/app.py", line 47, in app_init
    db_client = AsyncIOMotorClient(settings.MONGO_CONNECTION_STRING).credirectDB
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/uri_parser.py", line 542, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 121, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 101, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 97, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: All nameservers failed to answer the query _mongodb._tcp.cluster0.cbxao41.mongodb.net. IN SRV: Server 127.0.0.53 UDP port 53 answered SERVFAIL

[2022-11-07 09:48:54 +0100] [905] [ERROR] Application startup failed. Exiting.
[2022-11-07 09:48:54 +0100] [905] [INFO] Worker exiting (pid: 905)
[2022-11-07 09:48:54 +0100] [787] [WARNING] Worker with pid 901 was terminated due to signal 15
[2022-11-07 09:48:54 +0100] [787] [WARNING] Worker with pid 903 was terminated due to signal 15
[2022-11-07 09:48:54 +0100] [787] [WARNING] Worker with pid 905 was terminated due to signal 15
[2022-11-07 09:48:54 +0100] [787] [WARNING] Worker with pid 880 was terminated due to signal 15
[2022-11-07 09:48:55 +0100] [787] [INFO] Shutting down: Master
[2022-11-07 09:48:55 +0100] [787] [INFO] Reason: Worker failed to boot.
[2022-11-07 10:17:07 +0100] [3610] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fb603f737f0>
  on_reload: <function OnReload.on_reload at 0x7fb603f73910>
  when_ready: <function WhenReady.when_ready at 0x7fb603f73a30>
  pre_fork: <function Prefork.pre_fork at 0x7fb603f73b50>
  post_fork: <function Postfork.post_fork at 0x7fb603f73c70>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fb603f73d90>
  worker_int: <function WorkerInt.worker_int at 0x7fb603f73eb0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fb603f98040>
  pre_exec: <function PreExec.pre_exec at 0x7fb603f98160>
  pre_request: <function PreRequest.pre_request at 0x7fb603f98280>
  post_request: <function PostRequest.post_request at 0x7fb603f98310>
  child_exit: <function ChildExit.child_exit at 0x7fb603f98430>
  worker_exit: <function WorkerExit.worker_exit at 0x7fb603f98550>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fb603f98670>
  on_exit: <function OnExit.on_exit at 0x7fb603f98790>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-07 10:17:07 +0100] [3610] [INFO] Starting gunicorn 20.1.0
[2022-11-07 10:17:07 +0100] [3610] [DEBUG] Arbiter booted
[2022-11-07 10:17:07 +0100] [3610] [INFO] Listening at: http://0.0.0.0:8000 (3610)
[2022-11-07 10:17:07 +0100] [3610] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-07 10:17:07 +0100] [3611] [INFO] Booting worker with pid: 3611
[2022-11-07 10:17:07 +0100] [3612] [INFO] Booting worker with pid: 3612
[2022-11-07 10:17:07 +0100] [3613] [INFO] Booting worker with pid: 3613
[2022-11-07 10:17:07 +0100] [3614] [INFO] Booting worker with pid: 3614
[2022-11-07 10:17:07 +0100] [3615] [INFO] Booting worker with pid: 3615
[2022-11-07 10:17:07 +0100] [3610] [DEBUG] 5 workers
[2022-11-07 10:17:07 +0100] [3611] [INFO] Started server process [3611]
[2022-11-07 10:17:07 +0100] [3611] [INFO] Waiting for application startup.
[2022-11-07 10:17:07 +0100] [3612] [INFO] Started server process [3612]
[2022-11-07 10:17:07 +0100] [3612] [INFO] Waiting for application startup.
[2022-11-07 10:17:07 +0100] [3614] [INFO] Started server process [3614]
[2022-11-07 10:17:07 +0100] [3614] [INFO] Waiting for application startup.
[2022-11-07 10:17:07 +0100] [3613] [INFO] Started server process [3613]
[2022-11-07 10:17:07 +0100] [3613] [INFO] Waiting for application startup.
[2022-11-07 10:17:07 +0100] [3615] [INFO] Started server process [3615]
[2022-11-07 10:17:07 +0100] [3615] [INFO] Waiting for application startup.
[2022-11-07 10:17:09 +0100] [3615] [INFO] Application startup complete.
[2022-11-07 10:17:09 +0100] [3612] [INFO] Application startup complete.
[2022-11-07 10:17:09 +0100] [3614] [INFO] Application startup complete.
[2022-11-07 10:17:09 +0100] [3613] [INFO] Application startup complete.
[2022-11-07 10:17:09 +0100] [3611] [INFO] Application startup complete.
[2022-11-07 10:17:33 +0100] [3610] [INFO] Handling signal: term
[2022-11-07 10:17:33 +0100] [3615] [INFO] Shutting down
[2022-11-07 10:17:33 +0100] [3611] [INFO] Shutting down
[2022-11-07 10:17:33 +0100] [3612] [INFO] Shutting down
[2022-11-07 10:17:33 +0100] [3614] [INFO] Shutting down
[2022-11-07 10:17:33 +0100] [3613] [INFO] Shutting down
[2022-11-07 10:17:33 +0100] [3615] [INFO] Waiting for application shutdown.
[2022-11-07 10:17:33 +0100] [3615] [INFO] Application shutdown complete.
[2022-11-07 10:17:33 +0100] [3615] [INFO] Finished server process [3615]
[2022-11-07 10:17:33 +0100] [3615] [INFO] Worker exiting (pid: 3615)
[2022-11-07 10:17:33 +0100] [3611] [INFO] Waiting for application shutdown.
[2022-11-07 10:17:33 +0100] [3611] [INFO] Application shutdown complete.
[2022-11-07 10:17:33 +0100] [3611] [INFO] Finished server process [3611]
[2022-11-07 10:17:33 +0100] [3611] [INFO] Worker exiting (pid: 3611)
[2022-11-07 10:17:33 +0100] [3612] [INFO] Waiting for application shutdown.
[2022-11-07 10:17:33 +0100] [3612] [INFO] Application shutdown complete.
[2022-11-07 10:17:33 +0100] [3614] [INFO] Waiting for application shutdown.
[2022-11-07 10:17:33 +0100] [3612] [INFO] Finished server process [3612]
[2022-11-07 10:17:33 +0100] [3614] [INFO] Application shutdown complete.
[2022-11-07 10:17:33 +0100] [3614] [INFO] Finished server process [3614]
[2022-11-07 10:17:33 +0100] [3612] [INFO] Worker exiting (pid: 3612)
[2022-11-07 10:17:33 +0100] [3614] [INFO] Worker exiting (pid: 3614)
[2022-11-07 10:17:33 +0100] [3613] [INFO] Waiting for application shutdown.
[2022-11-07 10:17:33 +0100] [3613] [INFO] Application shutdown complete.
[2022-11-07 10:17:33 +0100] [3613] [INFO] Finished server process [3613]
[2022-11-07 10:17:33 +0100] [3613] [INFO] Worker exiting (pid: 3613)
[2022-11-07 10:17:33 +0100] [3610] [INFO] Shutting down: Master
[2022-11-07 11:52:52 +0100] [7120] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f3873a3f7f0>
  on_reload: <function OnReload.on_reload at 0x7f3873a3f910>
  when_ready: <function WhenReady.when_ready at 0x7f3873a3fa30>
  pre_fork: <function Prefork.pre_fork at 0x7f3873a3fb50>
  post_fork: <function Postfork.post_fork at 0x7f3873a3fc70>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f3873a3fd90>
  worker_int: <function WorkerInt.worker_int at 0x7f3873a3feb0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f3873a64040>
  pre_exec: <function PreExec.pre_exec at 0x7f3873a64160>
  pre_request: <function PreRequest.pre_request at 0x7f3873a64280>
  post_request: <function PostRequest.post_request at 0x7f3873a64310>
  child_exit: <function ChildExit.child_exit at 0x7f3873a64430>
  worker_exit: <function WorkerExit.worker_exit at 0x7f3873a64550>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f3873a64670>
  on_exit: <function OnExit.on_exit at 0x7f3873a64790>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-07 11:52:52 +0100] [7120] [INFO] Starting gunicorn 20.1.0
[2022-11-07 11:52:52 +0100] [7120] [DEBUG] Arbiter booted
[2022-11-07 11:52:52 +0100] [7120] [INFO] Listening at: http://0.0.0.0:8000 (7120)
[2022-11-07 11:52:52 +0100] [7120] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-07 11:52:52 +0100] [7121] [INFO] Booting worker with pid: 7121
[2022-11-07 11:52:52 +0100] [7122] [INFO] Booting worker with pid: 7122
[2022-11-07 11:52:52 +0100] [7123] [INFO] Booting worker with pid: 7123
[2022-11-07 11:52:52 +0100] [7124] [INFO] Booting worker with pid: 7124
[2022-11-07 11:52:52 +0100] [7125] [INFO] Booting worker with pid: 7125
[2022-11-07 11:52:52 +0100] [7120] [DEBUG] 5 workers
[2022-11-07 11:52:53 +0100] [7121] [INFO] Started server process [7121]
[2022-11-07 11:52:53 +0100] [7121] [INFO] Waiting for application startup.
[2022-11-07 11:52:53 +0100] [7123] [INFO] Started server process [7123]
[2022-11-07 11:52:53 +0100] [7123] [INFO] Waiting for application startup.
[2022-11-07 11:52:53 +0100] [7122] [INFO] Started server process [7122]
[2022-11-07 11:52:53 +0100] [7122] [INFO] Waiting for application startup.
[2022-11-07 11:52:53 +0100] [7124] [INFO] Started server process [7124]
[2022-11-07 11:52:53 +0100] [7124] [INFO] Waiting for application startup.
[2022-11-07 11:52:53 +0100] [7125] [INFO] Started server process [7125]
[2022-11-07 11:52:53 +0100] [7125] [INFO] Waiting for application startup.
[2022-11-07 11:52:54 +0100] [7121] [INFO] Application startup complete.
[2022-11-07 11:52:54 +0100] [7124] [INFO] Application startup complete.
[2022-11-07 11:52:54 +0100] [7125] [INFO] Application startup complete.
[2022-11-07 11:52:54 +0100] [7122] [INFO] Application startup complete.
[2022-11-07 11:52:54 +0100] [7123] [INFO] Application startup complete.
